modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${modlicense}"
issueTrackerURL="${modissues}"
[[mods]]
modId="${modid}"
version="${version}"
displayName="${modname}"
displayURL="${modsources}"
logoFile="logo.png"
authors="${modauthor}"
displayTest="NONE"
description='''${moddesc}'''
[[dependencies.${modid}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${modid}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
